<a href="https://colab.research.google.com/github/mbozdal/swatDimension/blob/main/swat.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
this is test2
import pandas as pd
import numpy as np

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
excel_data = pd.read_excel('/content/drive/MyDrive/SWaT_Dataset_Attack_v0.xlsx')

data = pd.DataFrame(excel_data)

data

/usr/local/lib/python3.8/dist-packages/openpyxl/worksheet/_reader.py:312: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)


Unnamed: 0 Unnamed: 1 Unnamed: 2 Unnamed: 3 Unnamed: 4  \
0                     Timestamp     FIT101     LIT101      MV101       P101   
1        28/12/2015 10:00:00 AM   2.427057   522.8467          2          2   
2        28/12/2015 10:00:01 AM   2.446274    522.886          2          2   
3        28/12/2015 10:00:02 AM   2.489191   522.8467          2          2   
4        28/12/2015 10:00:03 AM    2.53435   522.9645          2          2   
...                         ...        ...        ...        ...        ...   
449915      2/1/2016 2:59:55 PM   2.559972   519.5495          2          2   
449916      2/1/2016 2:59:56 PM   2.549082   520.4131          2          2   
449917      2/1/2016 2:59:57 PM   2.531467   520.6878          2          2   
449918      2/1/2016 2:59:58 PM   2.521218   520.7271          2          2   
449919      2/1/2016 2:59:59 PM   2.501681   521.1196          2          2   

       Unnamed: 5 Unnamed: 6 Unnamed: 7 Unnamed: 8 Unnamed: 9  ...  \
0            P102     AIT201     AIT202     AIT203     FIT201  ...   
1               1   262.0161   8.396437   328.6337   2.445391  ...   
2               1   262.0161   8.396437   328.6337   2.445391  ...   
3               1   262.0161   8.394514   328.6337   2.442316  ...   
4               1   262.0161   8.394514   328.6337   2.442316  ...   
...           ...        ...        ...        ...        ...  ...   
449915          1   168.0979   8.638683   301.9226   2.459488  ...   
449916          1   168.0979   8.638683   301.9226   2.459488  ...   
449917          1   168.0979   8.638683   301.9226   2.460129  ...   
449918          1   168.0979   8.638683   301.9226   2.460129  ...   
449919          1   168.0979   8.638683   301.9226   2.458206  ...   

       Unnamed: 43 Unnamed: 44 Unnamed: 45 Unnamed: 46 Unnamed: 47  \
0             P501        P502      PIT501      PIT502      PIT503   
1                2           1    250.8652    1.649953    189.5988   
2                2           1    250.8652    1.649953    189.6789   
3                2           1    250.8812    1.649953    189.6789   
4                2           1    250.8812    1.649953    189.6148   
...            ...         ...         ...         ...         ...   
449915           2           1    251.1535    0.865024     189.022   
449916           2           1    251.0734    0.865024    188.9259   
449917           2           1    251.0734    0.865024    188.9259   
449918           2           1    251.0734    0.865024    188.9259   
449919           2           1    251.0734    0.865024    188.9259   

       Unnamed: 48 Unnamed: 49 Unnamed: 50 Unnamed: 51    Unnamed: 52  
0           FIT601        P601        P602        P603  Normal/Attack  
1         0.000128           1           1           1         Normal  
2         0.000128           1           1           1         Normal  
3         0.000128           1           1           1         Normal  
4         0.000128           1           1           1         Normal  
...            ...         ...         ...         ...            ...  
449915           0           1           1           1         Normal  
449916           0           1           1           1         Normal  
449917           0           1           1           1         Normal  
449918           0           1           1           1         Normal  
449919           0           1           1           1         Normal  

[449920 rows x 53 columns]

In [ ]:
data = data.to_numpy() 

In [ ]:
data.shape

(449920, 53)

In [ ]:
data = data[1:, :]
data.shape

(449919, 53)

In [ ]:
data_new = data.copy() # data yı değiştirince 

In [ ]:
data_new[:,0][7195:7205]

array([' 28/12/2015 11:59:55 AM', ' 28/12/2015 11:59:56 AM',
       ' 28/12/2015 11:59:57 AM', ' 28/12/2015 11:59:58 AM',
       ' 28/12/2015 11:59:59 AM', ' 28/12/2015 12:00:00 PM',
       ' 28/12/2015 12:00:01 PM', ' 28/12/2015 12:00:02 PM',
       ' 28/12/2015 12:00:03 PM', ' 28/12/2015 12:00:04 PM'], dtype=object)

In [ ]:
from datetime import datetime

In [ ]:
data[:,0] = [datetime.strptime(dt, " %d/%m/%Y %H:%M:%S %p") for dt in data[:,0]]

In [ ]:
data = data[data[:,0].argsort()]

In [ ]:
data.shape

(449919, 53)

In [ ]:
data[:,0][7195:30000]

array([datetime.datetime(2015, 12, 28, 2, 59, 55),
       datetime.datetime(2015, 12, 28, 2, 59, 56),
       datetime.datetime(2015, 12, 28, 2, 59, 57), ...,
       datetime.datetime(2015, 12, 28, 9, 19, 57),
       datetime.datetime(2015, 12, 28, 9, 19, 58),
       datetime.datetime(2015, 12, 28, 9, 19, 59)], dtype=object)

In [ ]:
df = pd.DataFrame(data)
df.head()

0  1         2  3  4  5         6         7         8   \
0 2015-12-28 01:00:00  0  634.2853  1  2  1  263.2979  8.365676  330.6844   
1 2015-12-28 01:00:01  0  634.0498  1  2  1  263.2979  8.364715  330.6844   
2 2015-12-28 01:00:02  0  633.6573  1  2  1  263.2979  8.364715  330.6844   
3 2015-12-28 01:00:03  0  633.5788  1  2  1  263.2979  8.364715  330.6844   
4 2015-12-28 01:00:04  0  633.1862  1  2  1  263.2979  8.364715  330.6844   

         9   ... 43 44        45        46        47        48 49 50 51  \
0  2.450646  ...  2  1  248.1415  1.746067  187.3238  0.000128  1  1  1   
1  2.450646  ...  2  1  248.1415  1.746067  187.3238  0.000128  1  1  1   
2  2.450646  ...  2  1  248.1415  1.746067  187.3238  0.000128  1  1  1   
3  2.450646  ...  2  1  248.1415  1.746067  187.3238  0.000128  1  1  1   
4  2.449364  ...  2  1  248.1415  1.746067  187.1635  0.000128  1  1  1   

       52  
0  Normal  
1  Normal  
2  Normal  
3  Normal  
4  Normal  

[5 rows x 53 columns]

In [ ]:
X = df.drop(52, axis=1) # etiketi y, geri kalan datamız
y = df[52]
X.shape, y.shape

((449919, 52), (449919,))

In [ ]:
type(X)

pandas.core.frame.DataFrame

In [ ]:
X = X.to_numpy()
y = y.to_numpy()
X.shape, y.shape

((449919, 52), (449919,))

In [ ]:
X = X[:,1:] # zamanı çıkarıyorum 
X.shape

(449919, 51)

In [ ]:
y

array(['Normal', 'Normal', 'Normal', ..., 'Normal', 'Normal', 'Normal'],
      dtype=object)

In [ ]:
np.unique(y, return_counts=True)

(array(['A ttack', 'Attack', 'Normal'], dtype=object),
 array([    37,  54584, 395298]))

In [ ]:
y = y == 'Normal'
y = y.astype('uint8')

In [ ]:
np.unique(y)

array([0, 1], dtype=uint8)

In [ ]:
# X is data
# y is label

X.shape, y.shape

((449919, 51), (449919,))

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
X_train.shape, X_test.shape

((359935, 51), (89984, 51))

In [ ]:
#from sklearn.pipeline import make_pipeline
#from sklearn.preprocessing import StandardScaler
#from sklearn.svm import SVC
#clf = make_pipeline(StandardScaler(), SVC(gamma='auto'))
#clf.fit(X_train, y_train)

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
scaler = StandardScaler()  # for normalization
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
X_train.shape, X_test.shape

((359935, 51), (89984, 51))

## GED

In [ ]:
import scipy.linalg

In [ ]:
X0 = X_train[y_train==0]
X1 = X_train[y_train==1]
X0.shape, X1.shape

((43750, 51), (316185, 51))

In [ ]:
S = np.cov(X0.T.astype(int)) 
R = np.cov(X1.T.astype(int))

In [ ]:
a = np.eye(51) * 0.0001
S = S + a
R = R + a

In [ ]:
S.shape, R.shape

((51, 51), (51, 51))

In [ ]:
def is_pos_def(x):
    return np.all(np.linalg.eigvals(x) > 0)

is_pos_def(R), is_pos_def(S)

(True, True)

In [ ]:

D,evecsGED = scipy.linalg.eigh(S,R, subset_by_index=[46, 50])
evecsGED /= np.sqrt(np.sum(evecsGED**2,axis=0))

comps_train = evecsGED.T@X_train.T
comps_test = evecsGED.T@X_test.T

comps_train.shape, comps_test.shape

((5, 359935), (5, 89984))

In [ ]:
D

array([   194.64777011,    387.47618725,    891.26590292,   1971.23060848,
       161844.20416419])

In [ ]:
comps_train = comps_train.T
comps_test = comps_test.T
comps_train.shape, comps_test.shape

((359935, 5), (89984, 5))

In [ ]:
X_train = np.array(comps_train, dtype=np.float)
X_test = np.array(comps_test, dtype=np.float)

X_train.shape, X_test.shape

<ipython-input-40-3435970db1f5>:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  X_train = np.array(comps_train, dtype=np.float)
<ipython-input-40-3435970db1f5>:2: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  X_test = np.array(comps_test, dtype=np.float)


((359935, 5), (89984, 5))

In [ ]:
y_train.shape, y_test.shape

((359935,), (89984,))

In [ ]:
X_train

array([[-3.75845969e-02, -1.48032393e-02,  2.98698571e-04,
         2.60154346e-01,  1.54982915e-02],
       [-8.28792333e-01,  4.52935492e-01, -3.02796276e-03,
        -3.10027763e+00,  2.01786858e-02],
       [ 1.13335733e-01,  6.00334174e-04,  4.49140077e-04,
         2.67721508e-01,  1.55423753e-02],
       ...,
       [ 8.94141296e-02,  2.73925721e-02,  3.96128932e-04,
         2.78929349e-01,  1.55356258e-02],
       [ 7.32066622e-02, -4.84989372e-03,  3.46992873e-04,
         2.39349815e-01,  1.55763122e-02],
       [ 2.21147264e+00, -2.69972246e-01, -6.97673662e-05,
        -3.40744858e-01,  1.65561323e-02]])

In [ ]:
scaler = StandardScaler()  # for normalization
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
X_train.shape, X_test.shape

((359935, 5), (89984, 5))

## PCA

In [ ]:
X.shape, y.shape

((449919, 51), (449919,))

In [ ]:
from sklearn.decomposition import PCA

In [ ]:
pca = PCA(n_components=5)
X_reduced_train = pca.fit_transform(X_train)
X_reduced_test = pca.fit_transform(X_test)
X_reduced_train.shape, X_reduced_test.shape

((359935, 5), (89984, 5))

In [ ]:
pca.explained_variance_ratio_

array([0.41391697, 0.11179632, 0.07481595, 0.06229041, 0.05281187])

In [ ]:
np.sum(pca.explained_variance_ratio_)

0.7156315239437787

In [ ]:
#X_train, X_test, y_train, y_test = train_test_split(X_reduced, y, test_size=0.2, random_state=42)
#X_train.shape, X_test.shape, y_train.shape, y_test.shape

In [ ]:
X_train = X_reduced_train
X_test = X_reduced_test
X_train.shape, X_test.shape

((359935, 2), (89984, 2))

In [ ]:
scaler = StandardScaler()  # for normalization
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
X_train.shape, X_test.shape

((359935, 2), (89984, 2))

## AutoEncoder

In [ ]:
X.shape, X_train.shape, X_test.shape

((449919, 51), (359935, 51), (89984, 51))

In [ ]:
input = Input(shape=(51,))
x = Dense(26, activation='relu')(input)
print(x.shape)
x = Dense(13, activation='relu')(x)
print(x.shape)
code = Dense(5, activation='relu', name='code')(x)
print(code.shape)
x = Dense(13, activation='relu')(code)
print(x.shape)
x = Dense(26, activation='relu')(x)
print(x.shape)
x = Dense(51)(x)
print(x.shape)

(None, 26)
(None, 13)
(None, 5)
(None, 13)
(None, 26)
(None, 51)


In [ ]:
model_ae = Model(inputs=input, outputs=x)
model_ae.compile(optimizer='adam', loss='mse')

In [ ]:
model_ae.fit(X_train, X_train,
                epochs=100,
                batch_size=32,
                validation_data=(X_test, X_test))

Epoch 1/100
11248/11248 [==============================] - 33s 3ms/step - loss: 0.1498 - val_loss: 0.0829
Epoch 2/100
11248/11248 [==============================] - 33s 3ms/step - loss: 0.0786 - val_loss: 0.0762
Epoch 3/100
11248/11248 [==============================] - 33s 3ms/step - loss: 0.0679 - val_loss: 0.0635
Epoch 4/100
11248/11248 [==============================] - 34s 3ms/step - loss: 0.0605 - val_loss: 0.0557
Epoch 5/100
11248/11248 [==============================] - 34s 3ms/step - loss: 0.0557 - val_loss: 0.0560
Epoch 6/100
11248/11248 [==============================] - 34s 3ms/step - loss: 0.0530 - val_loss: 0.0477
Epoch 7/100
11248/11248 [==============================] - 33s 3ms/step - loss: 0.0515 - val_loss: 0.0485
Epoch 8/100
11248/11248 [==============================] - 34s 3ms/step - loss: 0.0496 - val_loss: 0.0461
Epoch 9/100
11248/11248 [==============================] - 35s 3ms/step - loss: 0.0491 - val_loss: 0.0467
Epoch 10/100
11248/11248 [====================

In [ ]:
encoder = Model(inputs=model_ae.input, outputs=model_ae.get_layer('code').output)

In [ ]:
X_train = encoder.predict(X_train)
X_test = encoder.predict(X_test)
X_train.shape, X_test.shape

2812/2812 [==============================] - 3s 1ms/step


((359935, 5), (89984, 5))

In [ ]:
scaler = StandardScaler()  # for normalization
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
X_train.shape, X_test.shape

((359935, 5), (89984, 5))

## Model

In [ ]:
import tensorflow as tf
from tensorflow.keras.layers import Input,Dense,concatenate,Flatten,GRU,Conv1D,Softmax, AveragePooling1D, MaxPool1D, Dropout, BatchNormalization, ReLU, Conv2D, MaxPool2D
from tensorflow.keras.models import Model
from tensorflow.keras import regularizers

In [ ]:
X_train = X_train.reshape(359935, 5, 1) # CNN için dönüşüm gerekli  X_train = X_train.reshape(359935, 5,8, 1) (samplesize,featuresize-dimesion1,varsa-dimension2,kanal)
X_test = X_test.reshape(89984, 5, 1)

In [ ]:
def block(input):
  tf.random.set_seed(42)
  conv11 = Conv1D(filters=16,kernel_size=5,padding='same')(input)
  conv22 = Conv1D(filters=16,kernel_size=5,padding='same')(input)
  conv33 = Conv1D(filters=16,kernel_size=5,padding='same')(input)  # kernel size dikkat
  #conv44 = Conv1D(filters=16,kernel_size=13,padding='same')(input)
  x = concatenate([conv11, conv22, conv33], axis=2)

  x = MaxPool1D(padding='same')(x) # padding same kaldır 
  x = BatchNormalization()(x)
  x = ReLU()(x)
  return x

tf.random.set_seed(42)
input = Input(shape=(5, 1))

conv1 = block(input)
conv2 = block(conv1)
conv3 = block(conv2)
conv4 = block(conv3)


gru1 = GRU(units=32, return_sequences=True)(conv4)
gru2 = GRU(units=32, return_sequences=True)(gru1)
gru_out = concatenate([gru1, gru2], axis=2)
gru3 = GRU(units=32)(gru_out)

flattened = Flatten()(conv3) # buraya ne yazarsanız onun sonucu. gru aktif değil. conv3 çıktısı alınır

out = Dense(1, activation='sigmoid')(flattened) # çıkış nöronumuz ,. binary classifier

model = Model(inputs=input, outputs=out)

model.compile(optimizer=tf.keras.optimizers.Adam(), loss=tf.keras.losses.BinaryCrossentropy(from_logits=True), metrics=['accuracy'])

In [ ]:
# gru olmadan sonuç
# conv katmanları sayısı değişebilir
# PCA uygula
# Parçalı denenebilir

In [ ]:
tf.random.set_seed(42)
hist = model.fit(X_train, y_train, epochs=5, batch_size=32, validation_data=(X_test, y_test))

Epoch 1/5


/usr/local/lib/python3.8/dist-packages/tensorflow/python/util/dispatch.py:1082: UserWarning: "`binary_crossentropy` received `from_logits=True`, but the `output` argument was produced by a sigmoid or softmax activation and thus does not represent logits. Was this intended?"
  return dispatch_target(*args, **kwargs)


11248/11248 [==============================] - 93s 8ms/step - loss: 0.1410 - accuracy: 0.9641 - val_loss: 0.1735 - val_accuracy: 0.9618
Epoch 2/5
11248/11248 [==============================] - 94s 8ms/step - loss: 0.1285 - accuracy: 0.9671 - val_loss: 0.1671 - val_accuracy: 0.9614
Epoch 3/5
11248/11248 [==============================] - 88s 8ms/step - loss: 0.1247 - accuracy: 0.9678 - val_loss: 0.1960 - val_accuracy: 0.9451
Epoch 4/5
11248/11248 [==============================] - 91s 8ms/step - loss: 0.1224 - accuracy: 0.9680 - val_loss: 0.1540 - val_accuracy: 0.9637
Epoch 5/5
11248/11248 [==============================] - 89s 8ms/step - loss: 0.1204 - accuracy: 0.9681 - val_loss: 0.1677 - val_accuracy: 0.9616


In [ ]:
x =  tf.round(model.predict(X_test))
pre = tf.keras.metrics.Precision()
pre.update_state(y_test, x)

recall = tf.keras.metrics.Recall()
recall.update_state(y_test, x)

acc = tf.keras.metrics.Accuracy()
acc.update_state(y_test, x)
  
fp = tf.keras.metrics.FalsePositives()
fn = tf.keras.metrics.FalseNegatives()
tp = tf.keras.metrics.TruePositives()
tn = tf.keras.metrics.TrueNegatives()
fp.update_state(y_test, x)
fn.update_state(y_test, x)
tp.update_state(y_test, x)
tn.update_state(y_test, x)

print(f'Precision: {pre.result().numpy()}')
print(f'Recall: {recall.result().numpy()}')
print(f'TP: {tp.result().numpy()}')
print(f'TN: {tn.result().numpy()}')
print(f'FP: {fp.result().numpy()}')
print(f'FN: {fn.result().numpy()}')

2812/2812 [==============================] - 5s 2ms/step
Precision: 0.9632784724235535
Recall: 0.999039351940155
TP: 79037.0
TN: 7858.0
FP: 3013.0
FN: 76.0


In [ ]:
2*pre.result().numpy()*recall.result().numpy()/(pre.result().numpy() +recall.result().numpy())

0.9966967222343351